name: 'Build/Test/Scan/Push Image'
inputs:
  target:
    description: Target or group to bake
    required: true
    type: string
  bakefile:
    description: Path to the bakefile
    required: true
    default: "docker-bake.hcl"
    type: string
  env-vars:
    description: A semicolon delimited list of environment variables to set as overrides for the bake definition
    required: false
    type: string
  test-image:
    description: Flag to test image once built
    default: true
    type: boolean
  scan-image:
    description: Flag to scan image for vulnerabilities once built
    default: true
    type: boolean
  push-image:
    description: Flag to push image once built
    default: false
    type: boolean
  ghcr-token:
    description: Username for authentication with GHCR.io
    required: true
    type: string
  dockerhub-username:
    description: Username for authentication with DockerHub
    required: true
    type: string
  dockerhub-token:
    description: Username for authentication with DockerHub
    required: true
    type: string
  gcp-json:
    description: JSON for authenticating Google Cloud Platform
    default: ""
    type: string
  snyk-org:
    description: Organization ID for Snyk
    default: ""
    type: string
  snyk-token:
    description: Token for authenticating with Snyk
    default: ""
    type: string
  soci-index:
    description: Flag to create SOCI index alongside image
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    # Setup dependencies and tools
    - name: Set up Just
      uses: extractions/setup-just@v2
      env:
        GITHUB_TOKEN: ${{ inputs.ghcr-token }}

    - uses: snyk/actions/setup@master

    - name: Snyk auth
      shell: bash
      run: |
        snyk auth ${{ inputs.snyk-token }}

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Authenticate to registries
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-token }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Login to GCAR us-central1
      continue-on-error: true
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: '${{ inputs.gcp-json }}'

    - name: Login to GCAR us
      continue-on-error: true
      uses: docker/login-action@v3
      with:
        registry: us-docker.pkg.dev
        username: _json_key
        password: '${{ inputs.gcp-json }}'

    - name: Login to GCAR asia
      continue-on-error: true
      uses: docker/login-action@v3
      with:
        registry: asia-docker.pkg.dev
        username: _json_key
        password: '${{ inputs.gcp-json }}'

    - name: Login to GCAR europe
      continue-on-error: true
      uses: docker/login-action@v3
      with:
        registry: europe-docker.pkg.dev
        username: _json_key
        password: '${{ inputs.gcp-json }}'

    # Build, test, and push image
    - name: Set up containerd
      if: ${{ inputs.soci-index == true }}
      uses: crazy-max/ghaction-setup-containerd@v3

    - name: Install soci
      if: ${{ inputs.soci-index == true }}
      uses: lerentis/soci-installer@v1.2.0
      with:
        install-dir: /usr/local/bin
        soci-release: v0.11.1

    - name: Build with oci format
      id: buildoci
      if: ${{ inputs.soci-index == true }}
      uses: docker/bake-action@v6
      with:
        targets: "${{ inputs.target }}"
        push: false
        load: true
        files: ${{ inputs.bakefile }}
        set: |
          *.output=type=oci,dest=/tmp/${{ inputs.target }}.tar

    - name: Build
      id: build
      if: ${{ inputs.soci-index == false }}
      uses: docker/bake-action@v6
      with:
        targets: "${{ inputs.target }}"
        push: false
        load: true
        files: ${{ inputs.bakefile }}

    - name: Test
      shell: bash
      run: |
        if [[ "${{ inputs.test-image }}" == "true" ]]; then
          just test "${{ inputs.target }}" "${{ inputs.bakefile }}"
        fi

    - name: Scan
      continue-on-error: true
      env:
        SNYK_ORG: ${{ inputs.snyk-org }}
      shell: bash
      run: |
        if [[ "${{ inputs.scan-image }}" == "true" ]]; then
          if [[ "${{ inputs.push-image }}" == "true" ]]; then
            just snyk-monitor "${{ inputs.target }}" "${{ inputs.bakefile }}"
          else
            just snyk-test "${{ inputs.target }}" "${{ inputs.bakefile }}"
          fi
        fi

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
          sarif_file: "container.sarif"
          category: "${{ inputs.target }}-snyk-vulnerabilities"

    - name: Create the soci v2 index for all the tags of the image, and push the images to their registries
      if: ${{ inputs.soci-index == true && inputs.push-image == true }}
      shell: bash
      run: |
        sudo ctr i import --digests /tmp/${{ inputs.target }}.tar
        docker buildx bake --builder=posit-builder -f docker-bake.hcl ${{ inputs.target }} --print | jq -r '.target[].tags[]' > /tmp/${{ inputs.target }}-tags
        xargs -i -a /tmp/${{ inputs.target }}-tags sudo soci convert {} {}
      #xargs -i -a /tmp/${{ inputs.target }}-tags /bin/bash -c 'if [[ "{}" == *"ghcr.io"* ]]; then sudo ctr i push --user "${{ github.actor }}:${{ inputs.ghcr-token }}" {}; elif [[ "{}" == *"docker.io"* ]]; then sudo ctr i push --user "${{ inputs.dockerhub-username }}:${{ inputs.dockerhub-token }}" {}; else echo "Not sure what to do with {}"; fi'
      #rm -f /tmp/${{ inputs.target }}-tags /tmp/${{ inputs.target }}.tar

    - name: Push - ${{ inputs.push-image }}
      if: ${{ inputs.soci-index == false && inputs.push-image == true }}
      uses: docker/bake-action@v6
      with:
        targets: "${{ inputs.target }}"
        push: ${{ inputs.push-image }}
        files: ${{ inputs.bakefile }}
