#!/bin/bash

set -e

echo '--> Showing .env file'
cat .env

# use xargs -0 (BSD) or xargs -d '\n' (GNU) to read env vars with spaces
# https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs
export $(grep -v '^#' .env | xargs)

echo '--> Showing Environment Variables'
echo "RSC_VERSION=${RSC_VERSION}"
echo "IMAGE_NAME=${IMAGE_NAME}"
echo "DOCKERFILE_PATH=${DOCKERFILE_PATH}"

docker build --build-arg RSC_VERSION=${RSC_VERSION} -f $DOCKERFILE_PATH -t $IMAGE_NAME .
