#!/bin/bash

# use xargs -0 (BSD) or xargs -d '\n' (GNU) to read env vars with spaces
# https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs
export $(grep -v '^#' .env | xargs)

docker build --build-arg RSC_VERSION=${RSC_VERSION} -f $DOCKERFILE_PATH -t $IMAGE_NAME .
