#!/bin/bash

set -e

echo "Building DOCKER_TAG=${DOCKER_TAG}"

apt-get update -qq && apt-get install -y jq

replace_version() {
  sed -i.bak "s/^RSC_VERSION=.*/RSC_VERSION=$1/g" ./.env
}

# if daily build
# replace version number and download url
if [[ "${DOCKER_TAG}" == *"daily"* ]]; then
  echo "--> Running daily"
  # get daily version
  rawurl=`curl -s https://cdn.rstudio.com/connect/latest-packages.json | jq -r '.packages | map(select(.platform == "ubuntu18/amd64"))[0].url'`

  
  echo "Got raw URL: $rawurl"
  # thanks to https://stackoverflow.com/a/44490624/6570011
  if [[ "$rawurl" =~ \_([a-z0-9\.\-]*) ]]; then
    match="${BASH_REMATCH[1]}"
    echo "Latest version found: $match"
    replace_version $match
  else
    # fail the build
    echo "ERROR parsing latest daily version"
    exit 1
  fi

elif [[ "${DOCKER_TAG}" =~ [0-9\.\-]+ ]]; then
  echo "DOCKER_TAG looks like a version number: ${DOCKER_TAG}"
  echo "Building DOCKER_TAG defined version"
  replace_version ${DOCKER_TAG}
else
  echo "No version customization necessary"
fi

echo '--> Showing .env file'
cat .env
