#!/bin/bash
# adapted from: https://windsock.io/automated-docker-image-builds-with-multiple-tags/

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
imageStart=$(expr index "$IMAGE_NAME" /)

repoName=${IMAGE_NAME:0:tagStart-1}
imageName=${IMAGE_NAME:imageStart:${#IMAGE_NAME}-tagStart-1}

if [ "${DOCKER_TAG}" != "latest" ]; then
  echo "Non-latest build - exiting and not tagging version number"
  exit 0
fi

# use xargs -0 (BSD) or xargs -d '\n' (GNU) to read env vars with spaces
# https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs
export $(grep -v '^#' .env | xargs)
tag=${RSP_VERSION}

echo "Pushing tag: ${repoName}:${tag}"

if [ -n "$tag" ]; then
  docker tag $IMAGE_NAME ${repoName}:${tag}
  docker push ${repoName}:${tag}
fi
