#!/bin/bash

# if daily build
# replace version number and download url
if [ "${DOCKER_TAG}" == "daily" ]; then
  # get daily version
  rawpage=`curl -s https://dailies.rstudio.com/rstudioserver/pro/bionic/x86_64/`
  if [[ "$rawpage" =~ rstudio-server-pro-([0-9\.\-]*)-amd64.deb ]]; then
    match="${BASH_REMATCH[1]}"
    echo "Latest version found: $match"
    sed -i '' "s/^RSP_VERSION=.*/RSP_VERSION=${match}/g" ./.env
    sed -i '' "s|^RSP_DOWNLOAD_URL=.*|RSP_DOWNLOAD_URL=https://dailies.rstudio.com/rstudioserver/pro/bionic/x86_64|g" ./.env
  else
    # fail the build
    echo "ERROR parsing latest daily version"
    exit 1
  fi
fi
