version: '3.5'
services:

  rsp-float-lic:
    hostname: rsp-float-lic
    image: rstudio/rstudio-server-pro-float-lic
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "PRODUCT=rsp"
        - "PORT=8989"
    networks:
      - default
    ports:
      - "8989:8989"
    environment:
      - "LICENSE=$RSP_FLOAT_LICENSE"

  rsc-float-lic:
    hostname: rsc-float-lic
    image: rstudio/rstudio-connect-float-lic
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "PRODUCT=connect"
        - "PORT=8999"
    networks:
      - default
    ports:
      - "8999:8999"
    environment:
      - "LICENSE=$RSC_FLOAT_LICENSE"

  rspm-float-lic:
    hostname: rspm-float-lic
    image: rstudio/rstudio-package-manager-float-lic
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "PRODUCT=rspm"
        - "PORT=8969"
    networks:
      - default
    ports:
      - "8969:8969"
    environment:
      - "LICENSE=$RSPM_FLOAT_LICENSE"

  # Commenting this one since we don't have a public docker image available
  # ssp-float-lic:
  #   hostname: ssp-float-lic
  #   image: rstudio/rstudio-ssp-float-lic
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     args:
  #       - "PRODUCT=ssp"
  #       - "PORT=8979"
  #   ports:
  #     - "8979:8979"
  #   environment:
  #     - "LICENSE=$SSP_FLOAT_LICENSE"
  #   networks:
  #     - default

networks:
  default:
    name: rstudio-docker-products
